package com

const val EMAIL = "email"
const val PHONE = "phone"
const val ID = "id"
const val USER_ID = "userID"
const val TITLE = "title"
const val GROUP = "group"
const val TYPE = "type"

const val ICON = "icon"
const val TRUTH = "truth"
const val TIME = "time"
const val TRUTH_STRING = "truthString"
const val LOGIN = "login"
const val STATEMENTS = "statements"
const val DESCRIPTION = "description"
const val QUESTION = "question"
const val QUESTIONS = "questions"
const val RESOURCES = "resources"
const val SETTINGS = "settings"
const val ANALYTICS = "analytics"
const val MAX_QUESTIONS = "maxQuestions"
const val DATA_PRIVACY = "dataPrivacy"
const val APP_CONFIG = "appConfig"
const val VERSION = "version"
const val TRIES = "tries"
const val DATE_TRY = "dateTry"
const val GAME = "game"
const val IS_BLOCKED = "isBlocked"
const val IS_LOG_IN = "isLogIn"
const val IS_RANDOM = "isRandom"
const val IS_ANONYMOUS = "isAnonymous"
const val IS_IN_SD = "isInSd"
const val IS_DEFAULT = "isDefault"
const val IS_PRIVATE = "isPrivate"
const val IS_PRESENTED = "isPresented"

const val PASSWORD = "password"
const val ANSWER = "answer"
const val MARK = "mark"
const val MARKS = "marks"
const val POINTS = "points"
const val COST = "cost"
const val PATH = "path"