package com.questionnaire

const val ID = "id"
const val USER_ID = "userId"
const val TITLE = "title"
const val IS_ANONYMOUS = "isAnonymous"
const val GROUP = "group"
const val TYPE = "type"
const val IS_IN_SD = "isInSd"
const val ICON = "icon"
const val TRUTH = "truth"
const val STATEMENTS = "statements"
const val DESCRIPTION = "description"
const val QUESTION = "question"
const val QUESTIONS = "questions"
const val RESOURCES = "resources"
const val SETTINGS = "settings"
const val ANALYTICS = "analytics"
const val PRIVACY = "privacy"
const val MARK = "mark"
const val PATH = "path"